#!/bin/bash
set -x

cd $OPENSHIFT_DATA_DIR/gradle-2.12/bin
echo -n "start"
#gradle build
java -Xms384m -Xmx496m -jar build/libs/*.jar --server.port=${OPENSHIFT_DIY_PORT} --server.address=${OPENSHIFT_DIY_IP} &