language: java
jdk:
    - oraclejdk8

script: scripts/run-tests.sh

deploy:
    provider: openshift
    user: m.ostapowicz@stud.elka.pw.edu.pl
    password:
        secure: uTYahQLzIrp/AzAgK7Wd4BlceEPKSwOiw5ozUomBUFSdDcJFjHlKRiF5Xh3/c2s+KHWRuP/6wFf60cV3Nh5jdExsHf/BNYhYaIi8eM/AHxfXIu6xv/4a+DRp5iAwlIzeXN6Uogb4ZP5iuiV6Tm8ycL225iFC/82dBBIdotOz2ThxSbUzQ/dt3WAlglANHfbem+OYS4IWCc6rTZ82k3HfYJlPF/9LYZtX8c/U0qn9c6wfezwryF5ghnCcn6PS7jCH8SGbUJHMphhRqtu85Na0MPjf381HxlwaYmqwHrjNA5jO3/lv2NNaMCbJLrqX+6iSDql9w6Q6+IlUm6ub/GB9GFgx7cHx3GjQsPxmNDN2xDWfm65s7DlTM7Wc9ArC/dgzqxPcwckyT0KaGI+4VYpv/wcOVxKavE2Bvu3yOJjTlFyTPvJUc8F+/bxLesnhzb79QnUxetqBUljv4LG+vsqSl//6VbfqAbuc8eysH6/sBkV5P95goKBMFh0LENm7HCjN0kj5BoEwz/cvP+BZTb/0Lm57ntC2PGJNA1jtcZXiAT3o6uQCTu6x7J8ncFMoyVd8X6OYoG5XxVyFIHZM7DbZAPzSg25MoU3Tj5jnxSBQCuCN2rq1clH/tqABu7rhZKRhzQeGeh2cjM8JQNzb5sGHK33eegAb3uLHUAzYaNv8/WE=
    app: chipanddale
    domain: pwprojects
    on:
        repo: pwPIK/PIK-Project
        branch: master
        condition: $TRAVIS_PULL_REQUEST = false