INSERT INTO MARKERS (LATITUDE, LONGITUDE) VALUES (1.054, 2.046);
INSERT INTO MARKERS (LATITUDE, LONGITUDE) VALUES (-15.80, 3.14);

INSERT INTO STASHES (MARKER_ID, DESCRIPTION) VALUES (1, 'First stash with Edam');
INSERT INTO STASHES (MARKER_ID, DESCRIPTION) VALUES (2, 'Second stash with Gouda');