INSERT INTO MARKERS (LATITUDE, LONGITUDE) VALUES (1.054, 2.046);
INSERT INTO MARKERS (LATITUDE, LONGITUDE) VALUES (-15.80, 3.14);

INSERT INTO STASHES (MARKER_ID, DESCRIPTION, VISITED) VALUES (1, 'First stash with Edam', 0);
INSERT INTO STASHES (MARKER_ID, DESCRIPTION, VISITED) VALUES (2, 'Second stash with Gouda', 1);