INSERT INTO MARKERS VALUES (1, 1.054, 2.046);
INSERT INTO MARKERS VALUES (2, -15.80, 3.14);

INSERT INTO STASHES VALUES (1, 1, 'First stash with Edam');
INSERT INTO STASHES VALUES (2, 2, 'Second stash with Gouda');