DROP ALL OBJECTS;

CREATE TABLE MARKERS (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    LATITUDE FLOAT NOT NULL,
    LONGITUDE FLOAT NOT NULL
);

CREATE TABLE STASHES (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    MARKER_ID BIGINT NOT NULL,
    DESCRIPTION VARCHAR(200),
    FOREIGN KEY (MARKER_ID) REFERENCES MARKERS(ID)
);